// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nomlnpnobdcbklnjgcpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vbWxucG5vYmRjYmtsbmpnY3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MjE4NzQsImV4cCI6MjA1MzA5Nzg3NH0.a-EeDAPz7IjPpFBqurXcHFuxYnuDAO_jzx37DS61CEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);